service: image-optimization

app: personal-project
org: lukhee

frameworkVersion: '2'

plugins:
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'

  environment:
    GROUP_TABLE: group-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GROUP_TABLE}

custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: Image Api
        description: Serverless application for image sharing
    models:
      - name: GroupImageRequest
        contentType: Application/json
        schema: ${file(models/create-group-request.json)}

functions:
  GetGroup:
    handler: src/lambda/http/getGroup.handler
    events:
      - http:
          method: get
          path: group
          cors: true

  CreateGroup:
    handler: src/lambda/http/createGroup.handler
    events:
      - http:
          method: post
          path: group
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new Group
            description: Create a new image
            requestModels:
              'application/json': GroupImageRequest

resources:
  Resources:
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    GroupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.GROUP_TABLE}
