service: image-optimization

app: personal-project
org: lukhee

frameworkVersion: '2'

plugins:
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'

  environment:
    IMAGE_TABLE: Images-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGE_TABLE}

custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: Image Api
        description: Serverless application for image sharing
    models:
      - name: ImageRequest
        contentType: Application/json
        schema: ${file(models/create-group-request.json)}

functions:
  GetImages:
    handler: src/lambda/http/getImages.handler
    events:
      - http:
          method: get
          path: images
          cors: true

  CreateImages:
    handler: src/lambda/http/createImages.handler
    events:
      - http:
          method: post
          path: images
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new image
            description: Create a new image
            requestModels:
              'application/json': GroupRequest

resources:
  Resources:
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        validateRequestBody: true
        validateRequestParameters: false

    ImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: imageUrl
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: createdAt
            KeyType: HASH
          - AttributeName: imageUrl
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.IMAGE_TABLE}
